from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

try:
    from psycopg2 import errors as psycopg2_errors
except Exception:  # pragma: no cover - psycopg2 is an optional import in unit tests
    psycopg2_errors = None


CORE_SCHEMA = "zsxq_core"


@dataclass(frozen=True)
class CoreTableSpec:
    name: str
    columns: tuple[str, ...]
    primary_key: tuple[str, ...] = ()
    unique_keys: tuple[tuple[str, ...], ...] = ()


CORE_TABLE_SPECS: tuple[CoreTableSpec, ...] = (
    CoreTableSpec("groups", ("group_id BIGINT", "name TEXT", "type TEXT", "background_url TEXT", "created_at TEXT", "imported_at TEXT"), ("group_id",)),
    CoreTableSpec("users", ("user_id BIGINT", "name TEXT", "alias TEXT", "avatar_url TEXT", "location TEXT", "description TEXT", "ai_comment_url TEXT", "imported_at TEXT", "created_at TEXT"), ("user_id",)),
    CoreTableSpec("topics", ("topic_id BIGINT", "group_id BIGINT", "type TEXT", "title TEXT", "annotation TEXT", "create_time TEXT", "modify_time TEXT", "updated_at TEXT", "imported_at TEXT", "digested BOOLEAN DEFAULT FALSE", "sticky BOOLEAN DEFAULT FALSE", "answered BOOLEAN DEFAULT FALSE", "silenced BOOLEAN DEFAULT FALSE", "user_liked BOOLEAN DEFAULT FALSE", "user_subscribed BOOLEAN DEFAULT FALSE", "likes_count BIGINT DEFAULT 0", "tourist_likes_count BIGINT DEFAULT 0", "rewards_count BIGINT DEFAULT 0", "comments_count BIGINT DEFAULT 0", "reading_count BIGINT DEFAULT 0", "readers_count BIGINT DEFAULT 0"), ("topic_id",)),
    CoreTableSpec("talks", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "text TEXT", "created_at TEXT"), ("id",), (("topic_id",),)),
    CoreTableSpec("articles", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "title TEXT", "article_id TEXT", "article_url TEXT", "inline_article_url TEXT", "created_at TEXT"), ("id",), (("topic_id",),)),
    CoreTableSpec("images", ("image_id BIGINT", "topic_id BIGINT", "comment_id BIGINT", "type TEXT", "thumbnail_url TEXT", "thumbnail_width BIGINT", "thumbnail_height BIGINT", "large_url TEXT", "large_width BIGINT", "large_height BIGINT", "original_url TEXT", "original_width BIGINT", "original_height BIGINT", "original_size BIGINT", "local_path TEXT", "created_at TEXT", "imported_at TEXT"), ("image_id",)),
    CoreTableSpec("comments", ("comment_id BIGINT", "group_id BIGINT", "topic_id BIGINT", "owner_user_id BIGINT", "parent_comment_id BIGINT", "repliee_user_id BIGINT", "text TEXT", "create_time TEXT", "likes_count BIGINT DEFAULT 0", "rewards_count BIGINT DEFAULT 0", "replies_count BIGINT DEFAULT 0", "sticky BOOLEAN DEFAULT FALSE", "created_at TEXT", "imported_at TEXT"), ("comment_id",)),
    CoreTableSpec("files", ("file_id BIGINT", "group_id BIGINT", "topic_id BIGINT", "name TEXT", "hash TEXT", "size BIGINT", "duration BIGINT", "download_count BIGINT", "create_time TEXT", "imported_at TEXT", "download_status TEXT DEFAULT 'pending'", "local_path TEXT", "download_time TEXT", "updated_at TEXT"), ("file_id",)),
    CoreTableSpec("topic_files", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "file_id BIGINT", "name TEXT", "hash TEXT", "size BIGINT", "duration BIGINT", "download_count BIGINT", "create_time TEXT", "created_at TEXT"), ("id",), (("topic_id", "file_id"),)),
    CoreTableSpec("file_topic_relations", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "file_id BIGINT", "topic_id BIGINT", "created_at TEXT"), ("id",), (("file_id", "topic_id"),)),
    CoreTableSpec("columns", ("column_id BIGINT", "group_id BIGINT", "name TEXT", "description TEXT", "cover_url TEXT", "topics_count BIGINT DEFAULT 0", "create_time TEXT", "last_topic_attach_time TEXT", "updated_at TEXT", "created_at TEXT", "imported_at TEXT"), ("column_id",)),
    CoreTableSpec("column_topics", ("topic_id BIGINT", "column_id BIGINT", "group_id BIGINT", "title TEXT", "text TEXT", "create_time TEXT", "attached_to_column_time TEXT", "updated_at TEXT", "imported_at TEXT"), ("topic_id",)),
    CoreTableSpec("topic_details", ("topic_id BIGINT", "group_id BIGINT", "type TEXT", "title TEXT", "full_text TEXT", "likes_count BIGINT DEFAULT 0", "comments_count BIGINT DEFAULT 0", "readers_count BIGINT DEFAULT 0", "digested BOOLEAN DEFAULT FALSE", "sticky BOOLEAN DEFAULT FALSE", "create_time TEXT", "modify_time TEXT", "raw_json TEXT", "imported_at TEXT", "updated_at TEXT"), ("topic_id",)),
    CoreTableSpec("topic_owners", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "user_id BIGINT", "owner_type TEXT DEFAULT 'talk'"), ("id",), (("topic_id", "owner_type"),)),
    CoreTableSpec("topic_columns", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "column_id BIGINT", "created_at TEXT"), ("id",), (("topic_id", "column_id"),)),
    CoreTableSpec("questions", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "questionee_user_id BIGINT", "text TEXT", "expired BOOLEAN DEFAULT FALSE", "anonymous BOOLEAN DEFAULT FALSE", "owner_questions_count BIGINT", "owner_join_time TEXT", "owner_status TEXT", "owner_location TEXT", "created_at TEXT"), ("id",), (("topic_id",),)),
    CoreTableSpec("answers", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "text TEXT", "created_at TEXT"), ("id",), (("topic_id",),)),
    CoreTableSpec("tags", ("tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id BIGINT", "tag_name TEXT", "hid TEXT", "topic_count BIGINT DEFAULT 0", "created_at TEXT"), ("tag_id",), (("group_id", "tag_name"),)),
    CoreTableSpec("topic_tags", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "tag_id BIGINT", "created_at TEXT"), ("id",), (("topic_id", "tag_id"),)),
    CoreTableSpec("likes", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "user_id BIGINT", "create_time TEXT", "imported_at TEXT"), ("id",)),
    CoreTableSpec("latest_likes", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "create_time TEXT", "created_at TEXT"), ("id",), (("topic_id", "owner_user_id", "create_time"),)),
    CoreTableSpec("like_emojis", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "emoji_key TEXT", "likes_count BIGINT DEFAULT 0", "created_at TEXT"), ("id",), (("topic_id", "emoji_key"),)),
    CoreTableSpec("user_liked_emojis", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "emoji_key TEXT", "created_at TEXT"), ("id",), (("topic_id", "emoji_key"),)),
    CoreTableSpec("videos", ("video_id BIGINT", "topic_id BIGINT", "size BIGINT", "duration BIGINT", "cover_url TEXT", "cover_width BIGINT", "cover_height BIGINT", "cover_local_path TEXT", "video_url TEXT", "download_status TEXT DEFAULT 'pending'", "local_path TEXT", "download_time TEXT", "imported_at TEXT"), ("video_id",)),
    CoreTableSpec("api_responses", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "succeeded BOOLEAN", "index_value TEXT", "files_count BIGINT", "request_url TEXT", "request_params TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("solutions", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "task_id BIGINT", "owner_user_id BIGINT", "text TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("solution_files", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "solution_id BIGINT", "file_id BIGINT", "name TEXT", "hash TEXT", "size BIGINT", "duration BIGINT", "download_count BIGINT", "create_time TEXT", "created_at TEXT"), ("id",), (("solution_id", "file_id"),)),
    CoreTableSpec("collection_log", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "start_time TEXT", "end_time TEXT", "total_files BIGINT DEFAULT 0", "new_files BIGINT DEFAULT 0", "status TEXT DEFAULT 'running'", "created_at TEXT"), ("id",)),
    CoreTableSpec("crawl_log", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id BIGINT", "crawl_type TEXT", "start_time TEXT", "end_time TEXT", "columns_count BIGINT DEFAULT 0", "topics_count BIGINT DEFAULT 0", "details_count BIGINT DEFAULT 0", "files_count BIGINT DEFAULT 0", "status TEXT DEFAULT 'running'", "error_message TEXT"), ("id",)),
    CoreTableSpec("daily_ai_reports", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id TEXT", "report_date TEXT", "topic_count BIGINT DEFAULT 0", "model TEXT", "prompt_version TEXT", "summary TEXT", "summary_markdown TEXT", "raw_json TEXT", "status TEXT DEFAULT 'completed'", "error TEXT", "created_at TEXT", "updated_at TEXT"), ("id",), (("group_id", "report_date"),)),
    CoreTableSpec("daily_stock_concepts", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id TEXT", "report_date TEXT", "stock_name TEXT", "stock_code TEXT", "market TEXT", "concepts_json TEXT", "reason TEXT", "topic_ids_json TEXT", "confidence DOUBLE PRECISION DEFAULT 0", "model TEXT", "status TEXT DEFAULT 'completed'", "error TEXT", "created_at TEXT", "updated_at TEXT"), ("id",), (("group_id", "report_date", "stock_name"),)),
    CoreTableSpec("stock_topic_analyses", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id TEXT", "stock_name TEXT", "stock_code TEXT", "market TEXT", "topic_ids_json TEXT", "concepts_json TEXT", "recommendation_count BIGINT DEFAULT 0", "summary_markdown TEXT", "model TEXT", "status TEXT DEFAULT 'completed'", "error TEXT", "created_at TEXT", "updated_at TEXT"), ("id",), (("group_id", "stock_name"),)),
    CoreTableSpec("file_ai_analyses", ("file_id BIGINT", "group_id BIGINT", "status TEXT DEFAULT 'completed'", "summary TEXT", "extracted_text TEXT", "extracted_text_preview TEXT", "content_type TEXT", "source_path TEXT", "source_size BIGINT", "model TEXT", "api_base TEXT", "wire_api TEXT", "reasoning_effort TEXT", "error_message TEXT", "created_at TEXT", "updated_at TEXT"), ("file_id",)),
    CoreTableSpec("accounts", ("id TEXT", "name TEXT", "cookie TEXT", "is_default BIGINT DEFAULT 0", "created_at TEXT", "updated_at TEXT"), ("id",)),
    CoreTableSpec("accounts_self", ("account_id TEXT", "uid TEXT", "name TEXT", "avatar_url TEXT", "location TEXT", "user_sid TEXT", "grade TEXT", "raw_json TEXT", "fetched_at TEXT"), ("account_id",)),
    CoreTableSpec("group_account_map", ("group_id TEXT", "account_id TEXT", "assigned_at TEXT"), ("group_id",)),
    CoreTableSpec("task_runs", ("task_id TEXT", "type TEXT", "status TEXT", "message TEXT", "result_json TEXT", "metadata_json TEXT", "created_at TEXT", "updated_at TEXT", "stopped BIGINT DEFAULT 0"), ("task_id",)),
    CoreTableSpec("task_logs", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "task_id TEXT", "message TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("task_locks", ("lock_key TEXT", "group_id TEXT", "category TEXT", "owner_task_id TEXT", "owner_task_type TEXT", "acquired_at TEXT", "expires_at TEXT", "heartbeat_at TEXT", "released_at TEXT", "release_reason TEXT"), ("lock_key",)),
    CoreTableSpec("zsxq_a_share_daily_mentions", ("group_id TEXT DEFAULT ''", "mention_date DATE", "company TEXT", "mentions_count BIGINT DEFAULT 0", "updated_at TIMESTAMPTZ DEFAULT NOW()"), ("group_id", "mention_date", "company")),
    CoreTableSpec("zsxq_a_share_processed_state", ("group_id TEXT DEFAULT ''", "source TEXT", "topic_id TEXT", "day DATE", "processed_at TIMESTAMPTZ DEFAULT NOW()"), ("group_id", "source", "topic_id", "day")),
    CoreTableSpec("zsxq_a_share_topic_stock_extractions", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id TEXT DEFAULT ''", "topic_id TEXT", "topic_date DATE", "stock_name TEXT", "stock_code TEXT", "market TEXT", "concepts_json TEXT", "reason TEXT", "confidence DOUBLE PRECISION DEFAULT 0", "model TEXT", "prompt_version TEXT", "created_at TIMESTAMPTZ DEFAULT NOW()", "updated_at TIMESTAMPTZ DEFAULT NOW()"), ("id",), (("group_id", "topic_id", "stock_name"),)),
    CoreTableSpec("zsxq_a_share_tdx_exports", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "exported_at TIMESTAMPTZ DEFAULT NOW()", "start_date DATE", "end_date DATE", "tdx_root TEXT", "ranking_top_n BIGINT", "total_written BIGINT DEFAULT 0", "unresolved_count BIGINT DEFAULT 0", "stock_basic_source TEXT DEFAULT 'unknown'", "source_detail TEXT", "backup_files JSONB DEFAULT '[]'::jsonb"), ("id",)),
    CoreTableSpec("zsxq_a_share_tdx_export_blocks", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "export_id BIGINT", "window_days BIGINT", "block_name TEXT", "block_code TEXT", "block_path TEXT", "written_count BIGINT DEFAULT 0", "skipped_count BIGINT DEFAULT 0", "skipped_companies JSONB DEFAULT '[]'::jsonb"), ("id",)),
)

CORE_TABLE_SPEC_BY_NAME = {spec.name: spec for spec in CORE_TABLE_SPECS}
SCHEMA_SETUP_COMMAND = "uv run manage-postgres-core-schema --apply"

CORE_INDEX_SPECS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("topics", ("group_id", "create_time")),
    ("topics", ("topic_id",)),
    ("comments", ("topic_id", "create_time")),
    ("files", ("file_id", "download_status", "create_time")),
    ("file_ai_analyses", ("file_id", "status")),
    ("task_runs", ("created_at", "status")),
    ("task_logs", ("task_id", "id")),
    ("task_locks", ("group_id", "category", "expires_at")),
    ("daily_stock_concepts", ("group_id", "report_date")),
    ("stock_topic_analyses", ("group_id", "stock_name")),
    ("accounts", ("id",)),
    ("accounts", ("is_default",)),
    ("group_account_map", ("account_id",)),
    ("column_topics", ("column_id",)),
    ("column_topics", ("group_id",)),
    ("topic_details", ("group_id",)),
    ("images", ("topic_id",)),
    ("images", ("comment_id",)),
    ("images", ("topic_id", "comment_id", "image_id")),
    ("files", ("topic_id",)),
    ("comments", ("group_id", "topic_id", "create_time")),
    ("videos", ("topic_id",)),
    ("talks", ("topic_id",)),
    ("articles", ("topic_id",)),
    ("likes", ("topic_id", "create_time")),
    ("like_emojis", ("topic_id",)),
    ("user_liked_emojis", ("topic_id",)),
    ("questions", ("topic_id",)),
    ("answers", ("topic_id",)),
    ("topic_files", ("topic_id", "file_id")),
    ("topic_tags", ("tag_id", "topic_id")),
    ("tags", ("group_id", "topic_count", "tag_name")),
    ("zsxq_a_share_daily_mentions", ("mention_date",)),
    ("zsxq_a_share_daily_mentions", ("group_id", "mention_date")),
    ("zsxq_a_share_processed_state", ("day",)),
    ("zsxq_a_share_processed_state", ("group_id", "day")),
    ("zsxq_a_share_topic_stock_extractions", ("group_id", "topic_date")),
    ("zsxq_a_share_topic_stock_extractions", ("group_id", "topic_id")),
    ("zsxq_a_share_tdx_export_blocks", ("export_id",)),
)

def quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _column_name(column_sql: str) -> str:
    return column_sql.strip().split()[0].strip('"')


def _constraint_name(table_name: str, columns: Iterable[str]) -> str:
    suffix = "_".join(columns)
    return f"{table_name}_{suffix}_key"[:60]


def _index_name(table_name: str, columns: Iterable[str]) -> str:
    suffix = "_".join(columns)
    return f"idx_{table_name}_{suffix}"[:60]


def _table_ref(table_name: str, schema: str = CORE_SCHEMA) -> str:
    return f"{quote_identifier(schema)}.{quote_identifier(table_name)}"


def _create_table_sql(spec: CoreTableSpec, schema: str = CORE_SCHEMA) -> str:
    columns = list(spec.columns)
    constraints: list[str] = []
    if spec.primary_key:
        pk_cols = ", ".join(quote_identifier(col) for col in spec.primary_key)
        constraints.append(f"PRIMARY KEY ({pk_cols})")
    for unique_key in spec.unique_keys:
        cols = ", ".join(quote_identifier(col) for col in unique_key)
        constraints.append(f"UNIQUE ({cols})")
    body = ",\n    ".join(columns + constraints)
    return f"CREATE TABLE IF NOT EXISTS {_table_ref(spec.name, schema)} (\n    {body}\n)"


def _alter_table_column_sql(table_name: str, column_sql: str, schema: str = CORE_SCHEMA) -> str:
    column_name = _column_name(column_sql)
    column_type = " ".join(column_sql.strip().split()[1:]) or "TEXT"
    column_type = column_type.replace(" PRIMARY KEY", "")
    column_type = column_type.replace(" NOT NULL", "")
    return f"ALTER TABLE {_table_ref(table_name, schema)} ADD COLUMN IF NOT EXISTS {quote_identifier(column_name)} {column_type}"


def _create_unique_sql(table_name: str, columns: tuple[str, ...], schema: str = CORE_SCHEMA) -> str:
    name = quote_identifier(_constraint_name(table_name, columns))
    cols = ", ".join(quote_identifier(col) for col in columns)
    return f"CREATE UNIQUE INDEX IF NOT EXISTS {name} ON {_table_ref(table_name, schema)} ({cols})"


def _create_index_sql(table_name: str, columns: tuple[str, ...], schema: str = CORE_SCHEMA) -> str:
    name = quote_identifier(_index_name(table_name, columns))
    cols = ", ".join(quote_identifier(col) for col in columns)
    return f"CREATE INDEX IF NOT EXISTS {name} ON {_table_ref(table_name, schema)} ({cols})"


def _tags_identity_backfill_sql(schema: str = CORE_SCHEMA) -> str:
    schema_literal = schema.replace("'", "''")
    table_ref = _table_ref("tags", schema)
    sequence_ref = f"{quote_identifier(schema)}.{quote_identifier('tags_tag_id_seq')}"
    sequence_literal = f"{schema}.tags_tag_id_seq".replace("'", "''")
    return f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = '{schema_literal}'
          AND table_name = 'tags'
          AND column_name = 'tag_id'
          AND is_identity = 'NO'
          AND column_default IS NULL
    ) THEN
        CREATE SEQUENCE IF NOT EXISTS {sequence_ref};
        EXECUTE 'ALTER SEQUENCE {sequence_ref} OWNED BY {table_ref}."tag_id"';
        PERFORM setval('{sequence_literal}', COALESCE((SELECT MAX("tag_id") FROM {table_ref}), 0) + 1, false);
        ALTER TABLE {table_ref} ALTER COLUMN "tag_id" SET DEFAULT nextval('{sequence_literal}'::regclass);
    END IF;
END $$""".strip()


def build_core_schema_sql(schema: str = CORE_SCHEMA, *, include_indexes: bool = True) -> list[str]:
    statements = [f"CREATE SCHEMA IF NOT EXISTS {quote_identifier(schema)}"]
    for spec in CORE_TABLE_SPECS:
        statements.append(_create_table_sql(spec, schema))
        for column_sql in spec.columns:
            statements.append(_alter_table_column_sql(spec.name, column_sql, schema))
        for unique_key in spec.unique_keys:
            statements.append(_create_unique_sql(spec.name, unique_key, schema))
    statements.append(_tags_identity_backfill_sql(schema))
    if include_indexes:
        for table_name, columns in CORE_INDEX_SPECS:
            statements.append(_create_index_sql(table_name, columns, schema))
    return statements


def execute_statements(conn, statements: Iterable[str]) -> None:
    with conn.cursor() as cur:
        for statement in statements:
            cur.execute(statement)
    conn.commit()


def ensure_core_schema(conn, *, include_indexes: bool = True) -> None:
    execute_statements(conn, build_core_schema_sql(include_indexes=include_indexes))


def is_schema_missing_error(exc: BaseException) -> bool:
    if psycopg2_errors is not None and isinstance(
        exc,
        (
            psycopg2_errors.UndefinedTable,
            psycopg2_errors.UndefinedColumn,
            psycopg2_errors.InvalidSchemaName,
            psycopg2_errors.UndefinedObject,
        ),
    ):
        return True
    text = str(exc).lower()
    return any(marker in text for marker in ("undefinedtable", "undefinedcolumn", "does not exist", "no such table"))


def schema_not_ready_message(exc: BaseException | None = None) -> str:
    suffix = f" Original error: {exc}" if exc else ""
    return f"PostgreSQL schema is not ready. Run `{SCHEMA_SETUP_COMMAND}` before starting runtime tasks.{suffix}"
