from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


CORE_SCHEMA = "zsxq_core"


@dataclass(frozen=True)
class CoreTableSpec:
    name: str
    columns: tuple[str, ...]
    primary_key: tuple[str, ...] = ()
    unique_keys: tuple[tuple[str, ...], ...] = ()


CORE_TABLE_SPECS: tuple[CoreTableSpec, ...] = (
    CoreTableSpec("groups", ("group_id BIGINT", "name TEXT", "type TEXT", "background_url TEXT", "created_at TEXT", "imported_at TEXT"), ("group_id",)),
    CoreTableSpec("users", ("user_id BIGINT", "name TEXT", "alias TEXT", "avatar_url TEXT", "location TEXT", "description TEXT", "ai_comment_url TEXT", "imported_at TEXT", "created_at TEXT"), ("user_id",)),
    CoreTableSpec("topics", ("topic_id BIGINT", "group_id BIGINT", "type TEXT", "title TEXT", "annotation TEXT", "create_time TEXT", "modify_time TEXT", "updated_at TEXT", "imported_at TEXT", "digested BOOLEAN DEFAULT FALSE", "sticky BOOLEAN DEFAULT FALSE", "answered BOOLEAN DEFAULT FALSE", "silenced BOOLEAN DEFAULT FALSE", "user_liked BOOLEAN DEFAULT FALSE", "user_subscribed BOOLEAN DEFAULT FALSE", "likes_count BIGINT DEFAULT 0", "tourist_likes_count BIGINT DEFAULT 0", "rewards_count BIGINT DEFAULT 0", "comments_count BIGINT DEFAULT 0", "reading_count BIGINT DEFAULT 0", "readers_count BIGINT DEFAULT 0"), ("topic_id",)),
    CoreTableSpec("talks", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "text TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("articles", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "title TEXT", "article_id TEXT", "article_url TEXT", "inline_article_url TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("images", ("image_id BIGINT", "topic_id BIGINT", "comment_id BIGINT", "type TEXT", "thumbnail_url TEXT", "thumbnail_width BIGINT", "thumbnail_height BIGINT", "large_url TEXT", "large_width BIGINT", "large_height BIGINT", "original_url TEXT", "original_width BIGINT", "original_height BIGINT", "original_size BIGINT", "local_path TEXT", "created_at TEXT", "imported_at TEXT"), ("image_id",)),
    CoreTableSpec("comments", ("comment_id BIGINT", "group_id BIGINT", "topic_id BIGINT", "owner_user_id BIGINT", "parent_comment_id BIGINT", "repliee_user_id BIGINT", "text TEXT", "create_time TEXT", "likes_count BIGINT DEFAULT 0", "rewards_count BIGINT DEFAULT 0", "replies_count BIGINT DEFAULT 0", "sticky BOOLEAN DEFAULT FALSE", "created_at TEXT", "imported_at TEXT"), ("comment_id",)),
    CoreTableSpec("files", ("file_id BIGINT", "group_id BIGINT", "topic_id BIGINT", "name TEXT", "hash TEXT", "size BIGINT", "duration BIGINT", "download_count BIGINT", "create_time TEXT", "imported_at TEXT", "download_status TEXT DEFAULT 'pending'", "local_path TEXT", "download_time TEXT", "updated_at TEXT"), ("file_id",)),
    CoreTableSpec("topic_files", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "file_id BIGINT", "name TEXT", "hash TEXT", "size BIGINT", "duration BIGINT", "download_count BIGINT", "create_time TEXT", "created_at TEXT"), ("id",), (("topic_id", "file_id"),)),
    CoreTableSpec("file_topic_relations", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "file_id BIGINT", "topic_id BIGINT", "created_at TEXT"), ("id",), (("file_id", "topic_id"),)),
    CoreTableSpec("columns", ("column_id BIGINT", "group_id BIGINT", "name TEXT", "description TEXT", "cover_url TEXT", "topics_count BIGINT DEFAULT 0", "create_time TEXT", "last_topic_attach_time TEXT", "updated_at TEXT", "created_at TEXT", "imported_at TEXT"), ("column_id",)),
    CoreTableSpec("column_topics", ("topic_id BIGINT", "column_id BIGINT", "group_id BIGINT", "title TEXT", "text TEXT", "create_time TEXT", "attached_to_column_time TEXT", "updated_at TEXT", "imported_at TEXT"), ("topic_id",)),
    CoreTableSpec("topic_details", ("topic_id BIGINT", "group_id BIGINT", "type TEXT", "title TEXT", "full_text TEXT", "likes_count BIGINT DEFAULT 0", "comments_count BIGINT DEFAULT 0", "readers_count BIGINT DEFAULT 0", "digested BOOLEAN DEFAULT FALSE", "sticky BOOLEAN DEFAULT FALSE", "create_time TEXT", "modify_time TEXT", "raw_json TEXT", "imported_at TEXT", "updated_at TEXT"), ("topic_id",)),
    CoreTableSpec("topic_owners", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "user_id BIGINT", "owner_type TEXT DEFAULT 'talk'"), ("id",), (("topic_id", "owner_type"),)),
    CoreTableSpec("topic_columns", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "column_id BIGINT", "created_at TEXT"), ("id",), (("topic_id", "column_id"),)),
    CoreTableSpec("questions", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "questionee_user_id BIGINT", "text TEXT", "expired BOOLEAN DEFAULT FALSE", "anonymous BOOLEAN DEFAULT FALSE", "owner_questions_count BIGINT", "owner_join_time TEXT", "owner_status TEXT", "owner_location TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("answers", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "text TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("tags", ("tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id BIGINT", "tag_name TEXT", "hid TEXT", "topic_count BIGINT DEFAULT 0", "created_at TEXT"), ("tag_id",), (("group_id", "tag_name"),)),
    CoreTableSpec("topic_tags", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "tag_id BIGINT", "created_at TEXT"), ("id",), (("topic_id", "tag_id"),)),
    CoreTableSpec("likes", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "user_id BIGINT", "create_time TEXT", "imported_at TEXT"), ("id",)),
    CoreTableSpec("latest_likes", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "owner_user_id BIGINT", "create_time TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("like_emojis", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "emoji_key TEXT", "likes_count BIGINT DEFAULT 0", "created_at TEXT"), ("id",)),
    CoreTableSpec("user_liked_emojis", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "emoji_key TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("videos", ("video_id BIGINT", "topic_id BIGINT", "size BIGINT", "duration BIGINT", "cover_url TEXT", "cover_width BIGINT", "cover_height BIGINT", "cover_local_path TEXT", "video_url TEXT", "download_status TEXT DEFAULT 'pending'", "local_path TEXT", "download_time TEXT", "imported_at TEXT"), ("video_id",)),
    CoreTableSpec("api_responses", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "succeeded BOOLEAN", "index_value TEXT", "files_count BIGINT", "request_url TEXT", "request_params TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("solutions", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "topic_id BIGINT", "task_id BIGINT", "owner_user_id BIGINT", "text TEXT", "created_at TEXT"), ("id",)),
    CoreTableSpec("solution_files", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "solution_id BIGINT", "file_id BIGINT", "name TEXT", "hash TEXT", "size BIGINT", "duration BIGINT", "download_count BIGINT", "create_time TEXT", "created_at TEXT"), ("id",), (("solution_id", "file_id"),)),
    CoreTableSpec("collection_log", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "start_time TEXT", "end_time TEXT", "total_files BIGINT DEFAULT 0", "new_files BIGINT DEFAULT 0", "status TEXT DEFAULT 'running'", "created_at TEXT"), ("id",)),
    CoreTableSpec("crawl_log", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id BIGINT", "crawl_type TEXT", "start_time TEXT", "end_time TEXT", "columns_count BIGINT DEFAULT 0", "topics_count BIGINT DEFAULT 0", "details_count BIGINT DEFAULT 0", "files_count BIGINT DEFAULT 0", "status TEXT DEFAULT 'running'", "error_message TEXT"), ("id",)),
    CoreTableSpec("daily_ai_reports", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "group_id TEXT", "report_date TEXT", "topic_count BIGINT DEFAULT 0", "model TEXT", "prompt_version TEXT", "summary TEXT", "summary_markdown TEXT", "raw_json TEXT", "status TEXT DEFAULT 'completed'", "error TEXT", "created_at TEXT", "updated_at TEXT"), ("id",), (("group_id", "report_date"),)),
    CoreTableSpec("file_ai_analyses", ("file_id BIGINT", "group_id BIGINT", "status TEXT DEFAULT 'completed'", "summary TEXT", "extracted_text TEXT", "extracted_text_preview TEXT", "content_type TEXT", "source_path TEXT", "source_size BIGINT", "model TEXT", "api_base TEXT", "wire_api TEXT", "reasoning_effort TEXT", "error_message TEXT", "created_at TEXT", "updated_at TEXT"), ("file_id",)),
    CoreTableSpec("accounts", ("id TEXT", "name TEXT", "cookie TEXT", "is_default BIGINT DEFAULT 0", "created_at TEXT", "updated_at TEXT"), ("id",)),
    CoreTableSpec("accounts_self", ("account_id TEXT", "uid TEXT", "name TEXT", "avatar_url TEXT", "location TEXT", "user_sid TEXT", "grade TEXT", "raw_json TEXT", "fetched_at TEXT"), ("account_id",)),
    CoreTableSpec("group_account_map", ("group_id TEXT", "account_id TEXT", "assigned_at TEXT"), ("group_id",)),
    CoreTableSpec("task_runs", ("task_id TEXT", "type TEXT", "status TEXT", "message TEXT", "result_json TEXT", "metadata_json TEXT", "created_at TEXT", "updated_at TEXT", "stopped BIGINT DEFAULT 0"), ("task_id",)),
    CoreTableSpec("task_logs", ("id BIGINT GENERATED BY DEFAULT AS IDENTITY", "task_id TEXT", "message TEXT", "created_at TEXT"), ("id",)),
)

CORE_TABLE_SPEC_BY_NAME = {spec.name: spec for spec in CORE_TABLE_SPECS}

CORE_INDEX_SPECS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("topics", ("group_id", "create_time")),
    ("topics", ("topic_id",)),
    ("comments", ("topic_id", "create_time")),
    ("files", ("file_id", "download_status", "create_time")),
    ("file_ai_analyses", ("file_id", "status")),
    ("task_runs", ("created_at", "status")),
    ("task_logs", ("task_id", "id")),
    ("accounts", ("id",)),
)

def quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _column_name(column_sql: str) -> str:
    return column_sql.strip().split()[0].strip('"')


def _constraint_name(table_name: str, columns: Iterable[str]) -> str:
    suffix = "_".join(columns)
    return f"{table_name}_{suffix}_key"[:60]


def _index_name(table_name: str, columns: Iterable[str]) -> str:
    suffix = "_".join(columns)
    return f"idx_{table_name}_{suffix}"[:60]


def _table_ref(table_name: str, schema: str = CORE_SCHEMA) -> str:
    return f"{quote_identifier(schema)}.{quote_identifier(table_name)}"


def _create_table_sql(spec: CoreTableSpec, schema: str = CORE_SCHEMA) -> str:
    columns = list(spec.columns)
    constraints: list[str] = []
    if spec.primary_key:
        pk_cols = ", ".join(quote_identifier(col) for col in spec.primary_key)
        constraints.append(f"PRIMARY KEY ({pk_cols})")
    for unique_key in spec.unique_keys:
        cols = ", ".join(quote_identifier(col) for col in unique_key)
        constraints.append(f"UNIQUE ({cols})")
    body = ",\n    ".join(columns + constraints)
    return f"CREATE TABLE IF NOT EXISTS {_table_ref(spec.name, schema)} (\n    {body}\n)"


def _alter_table_column_sql(table_name: str, column_sql: str, schema: str = CORE_SCHEMA) -> str:
    column_name = _column_name(column_sql)
    column_type = " ".join(column_sql.strip().split()[1:]) or "TEXT"
    column_type = column_type.replace(" PRIMARY KEY", "")
    column_type = column_type.replace(" NOT NULL", "")
    return f"ALTER TABLE {_table_ref(table_name, schema)} ADD COLUMN IF NOT EXISTS {quote_identifier(column_name)} {column_type}"


def _create_unique_sql(table_name: str, columns: tuple[str, ...], schema: str = CORE_SCHEMA) -> str:
    name = quote_identifier(_constraint_name(table_name, columns))
    cols = ", ".join(quote_identifier(col) for col in columns)
    return f"CREATE UNIQUE INDEX IF NOT EXISTS {name} ON {_table_ref(table_name, schema)} ({cols})"


def _create_index_sql(table_name: str, columns: tuple[str, ...], schema: str = CORE_SCHEMA) -> str:
    name = quote_identifier(_index_name(table_name, columns))
    cols = ", ".join(quote_identifier(col) for col in columns)
    return f"CREATE INDEX IF NOT EXISTS {name} ON {_table_ref(table_name, schema)} ({cols})"


def _tags_identity_backfill_sql(schema: str = CORE_SCHEMA) -> str:
    schema_literal = schema.replace("'", "''")
    table_ref = _table_ref("tags", schema)
    sequence_ref = f"{quote_identifier(schema)}.{quote_identifier('tags_tag_id_seq')}"
    sequence_literal = f"{schema}.tags_tag_id_seq".replace("'", "''")
    return f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = '{schema_literal}'
          AND table_name = 'tags'
          AND column_name = 'tag_id'
          AND is_identity = 'NO'
          AND column_default IS NULL
    ) THEN
        CREATE SEQUENCE IF NOT EXISTS {sequence_ref};
        EXECUTE 'ALTER SEQUENCE {sequence_ref} OWNED BY {table_ref}."tag_id"';
        PERFORM setval('{sequence_literal}', COALESCE((SELECT MAX("tag_id") FROM {table_ref}), 0) + 1, false);
        ALTER TABLE {table_ref} ALTER COLUMN "tag_id" SET DEFAULT nextval('{sequence_literal}'::regclass);
    END IF;
END $$""".strip()


def build_core_schema_sql(schema: str = CORE_SCHEMA, *, include_indexes: bool = True) -> list[str]:
    statements = [f"CREATE SCHEMA IF NOT EXISTS {quote_identifier(schema)}"]
    for spec in CORE_TABLE_SPECS:
        statements.append(_create_table_sql(spec, schema))
        for column_sql in spec.columns:
            statements.append(_alter_table_column_sql(spec.name, column_sql, schema))
        for unique_key in spec.unique_keys:
            statements.append(_create_unique_sql(spec.name, unique_key, schema))
    statements.append(_tags_identity_backfill_sql(schema))
    if include_indexes:
        for table_name, columns in CORE_INDEX_SPECS:
            statements.append(_create_index_sql(table_name, columns, schema))
    return statements


def execute_statements(conn, statements: Iterable[str]) -> None:
    with conn.cursor() as cur:
        for statement in statements:
            cur.execute(statement)
    conn.commit()


def ensure_core_schema(conn, *, include_indexes: bool = True) -> None:
    execute_statements(conn, build_core_schema_sql(include_indexes=include_indexes))
