import unittest

from backend.storage.postgres_core_schema import (
    CORE_SCHEMA,
    CORE_TABLE_SPECS,
    build_core_schema_sql,
    schema_not_ready_message,
)


class PostgresCoreSchemaTests(unittest.TestCase):
    def test_core_schema_sql_contains_schema_tables_and_indexes(self):
        sql = "\n".join(build_core_schema_sql())

        self.assertIn(f'CREATE SCHEMA IF NOT EXISTS "{CORE_SCHEMA}"', sql)
        self.assertIn(f'CREATE TABLE IF NOT EXISTS "{CORE_SCHEMA}"."topics"', sql)
        self.assertIn(f'CREATE TABLE IF NOT EXISTS "{CORE_SCHEMA}"."files"', sql)
        self.assertIn("tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY", sql)
        self.assertIn('CREATE UNIQUE INDEX IF NOT EXISTS "tags_group_id_tag_name_key"', sql)
        self.assertIn(f'CREATE TABLE IF NOT EXISTS "{CORE_SCHEMA}"."zsxq_a_share_daily_mentions"', sql)
        self.assertIn(f'CREATE TABLE IF NOT EXISTS "{CORE_SCHEMA}"."zsxq_a_share_tdx_exports"', sql)
        self.assertIn('CREATE INDEX IF NOT EXISTS "idx_zsxq_a_share_daily_mentions_group_id_mention_date"', sql)
        self.assertNotIn("source_schema TEXT", sql)
        self.assertNotIn(f'CREATE TABLE IF NOT EXISTS "{CORE_SCHEMA}"."record_sources"', sql)
        self.assertIn("CREATE INDEX IF NOT EXISTS", sql)

    def test_expected_core_tables_exist_in_schema_sql(self):
        sql = "\n".join(build_core_schema_sql())

        for spec in CORE_TABLE_SPECS:
            self.assertIn(f'CREATE TABLE IF NOT EXISTS "{CORE_SCHEMA}"."{spec.name}"', sql)

    def test_schema_not_ready_message_points_to_setup_command(self):
        self.assertIn("uv run manage-postgres-core-schema --apply", schema_not_ready_message(RuntimeError("missing")))


if __name__ == "__main__":
    unittest.main()
