import unittest
from unittest.mock import patch

from backend.storage.db_compat import (
    CompatRow,
    connect,
    _parse_pragma_table_info,
    _should_return_id,
    _strip_env_value,
    _translate_sql,
    schema_name_for_path,
)


class DbCompatTests(unittest.TestCase):
    def test_schema_name_is_stable_and_namespaced_by_path(self):
        first = schema_name_for_path("output/databases/1/zsxq_topics_1.db")
        second = schema_name_for_path("output/databases/2/zsxq_topics_1.db")

        self.assertTrue(first.startswith("zsxq_zsxq_topics_1_"))
        self.assertNotEqual(first, second)

    def test_translates_sqlite_upsert_for_known_primary_key_table(self):
        sql = _translate_sql(
            "INSERT OR REPLACE INTO topics (topic_id, group_id, type) VALUES (?, ?, ?)"
        )

        self.assertIn("ON CONFLICT (topic_id) DO UPDATE", sql)
        self.assertIn("VALUES (%s, %s, %s)", sql)

    def test_translates_quoted_sqlite_upsert_for_known_primary_key_table(self):
        sql = _translate_sql(
            'INSERT OR REPLACE INTO "topics" ("topic_id", "group_id") VALUES (?, ?)'
        )

        self.assertIn("ON CONFLICT (topic_id) DO UPDATE", sql)
        self.assertIn("VALUES (%s, %s)", sql)

    def test_keeps_replace_as_insert_when_no_unique_target_is_known(self):
        sql = _translate_sql("INSERT OR REPLACE INTO talks (topic_id, text) VALUES (?, ?)")

        self.assertNotIn("ON CONFLICT", sql)
        self.assertIn("INSERT INTO talks", sql)

    def test_translates_autoincrement_and_limit_offset(self):
        create_sql = _translate_sql("id INTEGER PRIMARY KEY AUTOINCREMENT")
        query_sql = _translate_sql("SELECT * FROM task_runs LIMIT -1 OFFSET ?")

        self.assertEqual("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", create_sql)
        self.assertEqual("SELECT * FROM task_runs OFFSET %s", query_sql)

    def test_create_table_translation_removes_foreign_keys(self):
        sql = _translate_sql(
            """
            CREATE TABLE IF NOT EXISTS comments (
                comment_id INTEGER PRIMARY KEY,
                parent_comment_id INTEGER,
                FOREIGN KEY (parent_comment_id) REFERENCES comments (comment_id)
            )
            """
        )

        self.assertNotIn("FOREIGN KEY", sql)
        self.assertIn("comment_id BIGINT PRIMARY KEY", sql)

    def test_env_value_strip_removes_matching_outer_quotes(self):
        self.assertEqual("postgres", _strip_env_value('"postgres"'))
        self.assertEqual("sqlite", _strip_env_value("'sqlite'"))
        self.assertEqual('"mixed', _strip_env_value('"mixed'))

    def test_connect_rejects_removed_sqlite_backend(self):
        with patch("backend.storage.db_compat.get_database_backend", return_value="sqlite"):
            with self.assertRaisesRegex(RuntimeError, "SQLite backend has been removed"):
                connect("removed.db")

    def test_compat_row_supports_index_and_column_access(self):
        row = CompatRow(("task-1", "running"), ("task_id", "status"))

        self.assertEqual("task-1", row[0])
        self.assertEqual("running", row["status"])
        self.assertEqual(["task_id", "status"], row.keys())

    def test_translates_insert_or_ignore_to_do_nothing(self):
        sql = _translate_sql("INSERT OR IGNORE INTO topics (topic_id, group_id) VALUES (?, ?)")

        self.assertIn("INSERT INTO topics", sql)
        self.assertIn("ON CONFLICT DO NOTHING", sql)

    def test_parse_pragma_table_info_accepts_quoted_names(self):
        self.assertEqual("topics", _parse_pragma_table_info('PRAGMA table_info("topics")'))
        self.assertIsNone(_parse_pragma_table_info("PRAGMA journal_mode=WAL"))

    def test_should_return_id_for_legacy_insert_tables_only(self):
        self.assertTrue(_should_return_id("INSERT INTO crawl_log (message) VALUES (%s)"))
        self.assertTrue(_should_return_id('INSERT INTO "crawl_log" ("message") VALUES (%s)'))
        self.assertTrue(_should_return_id("INSERT INTO solutions (name) VALUES (%s)"))
        self.assertFalse(_should_return_id("INSERT INTO topics (topic_id) VALUES (%s)"))
        self.assertFalse(_should_return_id("INSERT INTO crawl_log (message) VALUES (%s) RETURNING id"))


if __name__ == "__main__":
    unittest.main()
